# Generated by Django 3.2 on 2021-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')], verbose_name='gender')),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='profile/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
